### ISSUE TITLE
1.5.0 broken, missing `requests` module

### ISSUE THREAD

**Issue by marco-m** [SHyx0rmZ/bitbucket-build-status-resource#9]
hello,

we are happily using this resource. It looks like that the latest tag 1.5.0 is broken? Here is what we get in our Concourse:

```
fetching shyxormz/bitbucket-build-status-resource@sha256:22bf81b662da0e3928b0406bd416d08aa4e0c7991430b96b549d7cbda54a78eb
8e3ba11ec2a2 [==========================================] 2.1MiB/2.1MiB
4c3549888888 [========================================] 40.9MiB/40.9MiB
dcccbacc0e9c [==========================================] 8.4KiB/8.4KiB
Traceback (most recent call last):
  File "/opt/resource/out", line 8, in <module>
    from bitbucket import BitbucketException, BitbucketCloudDriver, BitbucketServerDriver, set_build_status
  File "/opt/resource/bitbucket/__init__.py", line 1, in <module>
    from .bitbucket import BitbucketOAuth, BitbucketDriver, BitbucketException, request_access_token, set_build_status
  File "/opt/resource/bitbucket/bitbucket.py", line 1, in <module>
    import requests
ImportError: No module named requests
```

**Comment by mockersf** [comment]
dependencies are now installed for python3, but python2 is also installed (as part of mercurial) and used by default:
```
# apk del python2
World updated, but the following packages are not removed due to:
  python2: mercurial
```

**Comment by marco-m-pix4d** [comment]
thanks!

**Comment by marco-m** [comment]
thanks!
